
-- =============================================================================
-- MIGRATION: 0009_seed_faqs
-- Description: Seed the 38 supplied FAQs
-- =============================================================================

-- Clear existing non-seeded FAQs if any, or just truncate and insert. 
-- We'll just truncate since we are seeding the complete list.
TRUNCATE TABLE public.faqs;

INSERT INTO public.faqs (question, answer, category, display_order, is_published) VALUES
  ('What makes Fluenciel different from other French institutes?', 'At Fluenciel, we believe that completing a batch should not mean completing your preparation. Depending on your programme, your Fluenciel journey includes: Interactive live classes Structured A1 → B2 learning Class summary after every class Regular assignments Doubt-solving sessions Mock tests during the course Exam-oriented practice Speaking, listening, reading and writing practice Feedback and progress evaluation Continued academic support after course completion Doubt-solving and mock-test support after the scheduled course duration Support towards your first attempt at your target examination, subject to the applicable course terms We don''t just teach you and say goodbye when the batch ends. Our aim is to continue supporting you after the scheduled course duration as you prepare for your first examination attempt.', 'General', 1, true),
  ('What happens after my batch duration is completed?', 'Your Fluenciel journey doesn''t end when your batch ends. For eligible programmes, we continue to support students after the scheduled course duration with applicable: Doubt-solving sessions Mock tests Examination practice Academic guidance Our goal is to help you continue practising, identify your weaknesses, and prepare for your  first attempt at your target examination. The exact post-course support available depends on the specific programme and its terms.', 'General', 2, true),
  ('Do I get mock tests after completing my course?', 'For eligible programmes, yes. Mock tests are provided during the course, and applicable programmes may also include additional mock-test opportunities after the scheduled course duration. This allows you to continue testing your preparation and identifying areas that need improvement before your examination.', 'General', 3, true),
  ('Can I ask doubts after completing my course?', 'For eligible programmes, yes. Our support doesn''t simply stop when the scheduled batch ends. Applicable programmes include continued doubt-solving support to help students clarify difficult concepts and continue their preparation.', 'General', 4, true),
  ('Why does Fluenciel provide support after the course?', 'Because we understand that finishing the syllabus and being ready for an examination are not always the same thing. Students may need additional practice, mock tests, feedback, and doubt-solving before they feel ready for their first attempt. That''s why our approach is designed to support students beyond the classroom and towards their examination.', 'General', 5, true),
  ('What is Fluenciel?', 'Fluenciel is a French-language education and exam-preparation company focused on helping students learn French and prepare for examinations such as TEF, TCF, DELF and DALF. Our programmes combine structured French learning, interactive classes, assignments, doubt-solving, mock tests, and exam-focused preparation.', 'GENERAL', 6, true),
  ('Is Fluenciel an online French institute?', 'Yes. Fluenciel primarily provides live online French classes, allowing students to learn from anywhere. Depending on the programme, classes may be offered in one-to-one or group formats.', 'GENERAL', 7, true),
  ('Who can join Fluenciel?', 'Our programmes are designed for: Complete beginners French learners Students preparing for TEF or TCF Students preparing for DELF or DALF Students planning to move abroad Working professionals College and university students Learners who want to improve their French communication skills', 'GENERAL', 8, true),
  ('Do I need previous knowledge of French?', 'Not necessarily. If you are a complete beginner, you can start from A', 'GENERAL', 9, true),
  ('If you already know French, we can help determine the appropriate level before enrolment. 10. What levels does Fluenciel offer?', 'Our structured learning pathway covers: A1 → A2 → B1 → B2 The appropriate level depends on your existing French knowledge and your learning objective.', 'GENERAL', 1, true),
  ('What is included in a Fluenciel course?', 'Depending on the programme, your course may include: Live interactive classes Structured curriculum Class summaries Assignments Speaking practice Listening practice Reading practice Writing practice Doubt-solving sessions Mock tests Exam-oriented practice Study materials Academic guidance The exact features included may vary depending on the course selected.', 'COURSES & LEARNING', 11, true),
  ('Are the classes interactive?', 'Yes. Our classes are designed to encourage active participation rather than simply listening to a teacher. Students may participate in: Speaking activities Conversations Role plays Listening activities Reading exercises Writing activities Vocabulary practice Exam-style tasks', 'COURSES & LEARNING', 12, true),
  ('Will I receive a summary after every class?', 'Yes. Students receive a class summary after each class covering important concepts, vocabulary, grammar, and other key points from the session. This makes revision easier and helps students stay organised.', 'COURSES & LEARNING', 13, true),
  ('Will I get assignments?', 'Yes. Assignments are provided regularly so students can practise what they have learned and reinforce their understanding outside the classroom.', 'COURSES & LEARNING', 14, true),
  ('Are doubt-solving sessions included?', 'Yes, applicable programmes include doubt-solving support. Students can use these sessions to clarify grammar, vocabulary, speaking, writing, reading, listening, and examination-related doubts.', 'COURSES & LEARNING', 15, true),
  ('Will I get mock tests?', 'Yes. Mock tests and exam-style practice are incorporated into applicable programmes. They help students: Understand their current level Become familiar with exam-style tasks Practise time management Identify weaknesses Track progress Build examination confidence', 'COURSES & LEARNING', 16, true),
  ('Does Fluenciel prepare students for TEF?', 'Yes. Our TEF-oriented programmes focus on the four core skills: Listening | Speaking | Reading | Writing along with examination-oriented practice and mock tests.', 'TEF, TCF, DELF & DALF', 17, true),
  ('Does Fluenciel prepare students for TCF?', 'Yes. We provide TCF-oriented preparation focusing on French language development, examination practice, and the relevant skills required for the applicable TCF format.', 'TEF, TCF, DELF & DALF', 18, true),
  ('Does Fluenciel prepare students for DELF?', 'Yes. Fluenciel offers preparation for relevant DELF levels, combining structured language learning with examination-oriented practice.', 'TEF, TCF, DELF & DALF', 19, true),
  ('Does Fluenciel prepare students for DALF?', 'Yes. Depending on the programme available, Fluenciel provides advanced French learning and DALF examination preparation.', 'TEF, TCF, DELF & DALF', 20, true),
  ('Does Fluenciel guarantee a particular exam score?', 'No. We provide structured preparation, practice, mock tests, and academic support, but examination results depend on the student''s preparation and performance as well as the official examination assessment. We do not guarantee a specific examination score or result.', 'TEF, TCF, DELF & DALF', 21, true),
  ('Do you register students for the official examination?', 'Fluenciel provides language training and examination preparation. Official examination registration, dates, centres, fees, and examination rules are determined by the relevant examination authorities. Students are responsible for completing their official examination registration.', 'TEF, TCF, DELF & DALF', 22, true),
  ('Are classes one-to-one or in groups?', 'Fluenciel may offer both one-to-one and group programmes, depending on the course. Please check the relevant course page for the format of your programme.', 'CLASSES & BATCHES', 23, true),
  ('How long is each class?', 'Class duration depends on the programme and batch. The exact schedule and class duration will be communicated before enrolment.', 'CLASSES & BATCHES', 24, true),
  ('Can I choose my class timing?', 'Timing availability depends on the programme, batch, teacher availability, and course format. One-to-one programmes may offer greater flexibility.', 'CLASSES & BATCHES', 25, true),
  ('What happens if I miss a class?', 'Students are expected to attend their scheduled classes. Missed classes do not automatically qualify for a refund. Any rescheduling or alternative arrangement will be subject to the applicable course policy and teacher availability.', 'CLASSES & BATCHES', 26, true),
  ('Can I change my batch?', 'A batch change may be possible in certain circumstances, depending on availability and the specific course terms. Batch changes are not guaranteed.', 'CLASSES & BATCHES', 27, true),
  ('How much do Fluenciel courses cost?', 'Course fees vary depending on: Programme Level Duration Course format One-to-one or group learning Examination preparation Additional services included Please check the relevant course page or contact our team for the current fee.', 'FEES & REFUNDS', 28, true),
  ('Do you offer payment plans?', 'Payment options may vary depending on the programme. Please contact the Fluenciel team for the payment options available for your selected course.', 'FEES & REFUNDS', 29, true),
  ('Do you provide refunds?', 'Fluenciel follows a non-refundable course-fee policy. Once a student enrols and payment has been received, the course fee is generally non￾refundable. Students should review the complete Refund & Cancellation Policy before making payment. This policy remains subject to any rights or remedies that cannot legally be excluded under applicable law.', 'FEES & REFUNDS', 30, true),
  ('What if I change my mind after purchasing a course?', 'Course fees are generally non-refundable if you change your mind after enrolment. We recommend reviewing the course structure, schedule, duration, inclusions, and applicable policies before making payment.', 'FEES & REFUNDS', 31, true),
  ('Will Fluenciel provide study material?', 'Yes, applicable programmes include educational resources and study materials. The exact materials provided depend on the course.', 'STUDY MATERIAL & SUPPORT', 32, true),
  ('Will I get speaking practice?', 'Yes. Speaking is an important part of our French-learning approach. Students participate in conversations, speaking activities, role plays, pronunciation practice, and where applicable, examination-style speaking tasks.', 'STUDY MATERIAL & SUPPORT', 33, true),
  ('Do you teach all four French skills?', 'Yes. Our programmes can incorporate: Listening — Compréhension orale Speaking — Expression orale Reading — Compréhension écrite Writing — Expression écrite The amount and format of practice may vary by programme and level.', 'STUDY MATERIAL & SUPPORT', 34, true),
  ('How do I know which level I should join?', 'If you already know some French, Fluenciel can help determine your appropriate level through an assessment or discussion with our team.', 'LEARNING JOURNEY', 35, true),
  ('How long does it take to reach B2?', 'The time required varies from student to student. It depends on: Starting level Previous French knowledge Class frequency Practice outside class Consistency Individual learning pace Fluenciel follows a structured A1 → B2 progression, but we do not guarantee that every student will reach a particular level within a fixed period.', 'LEARNING JOURNEY', 36, true),
  ('Can I learn French while working or studying?', 'Yes. We offer programmes designed for different schedules, including options that may suit working professionals and students.', 'LEARNING JOURNEY', 37, true),
  ('Can I join if I am preparing for immigration to Canada?', 'Yes. Fluenciel provides French training and examination preparation for students who are learning French for goals such as Canadian immigration. However, Fluenciel does not provide immigration decisions and does not guarantee visa, permanent residence, or immigration outcomes.', 'LEARNING JOURNEY', 38, true);
